#!/bin/bash
#
# This monstrosity of a script is used to run and create a windows vm

# QEMU Binary
QEMU=/usr/bin/qemu-system-x86_64

#####################################################################################################
####################################     QEMU COMMAND     ###########################################
#####################################################################################################
COMMAND=( $QEMU


########## HOST SETUP ###############################################################################

    # Name the VM and give each thread a unique name from the hosts perspective
    -name guest=windows,\
debug-threads=on

    ##### Not sure what this is for #####
    # TODO: ?
#    -object secret,
#id=masterKey0,
#format=raw,
#file=/var/lib/libvirt/qemu/domain-1-windows/master-key.aes



########## MACHINE SETUP ############################################################################

    # Machine emulation settings
    -machine pc-i440fx-2.8,\
accel=kvm,\
usb=off,\
dump-guest-core=off

    # Choose virtual CPU features
    -cpu host,\
hv_time,\
hv_relaxed,\
hv_vapic,\
hv_spinlocks=0x1fff

    # Configure amout of system RAM
    -m 8192

    # VNC Setup
    -vnc 0.0.0.0:0

    # Pins VM sysmem so pages are never swapped out
    -realtime mlock=on

    # Virtual CPU configuration
    -smp 8,\
sockets=1,\
cores=4,\
threads=2

    ##### Dont know what this does #####
    # TODO: ?
    -uuid e1e39888-5f76-4ee0-860b-2503ac2adde0

    # Disable HPET timing mechanicsm
    -no-hpet
    # TODO: what does this do?
    -boot strict=on

    # Set date and time for VM
    -rtc base=localtime,\
driftfix=slew



########## DRIVES SETUP #############################################################################

    # Configure root fs drive
    -drive file=/data/vm-disks/windows.img,\
format=raw,\
if=none,\
id=drive-virtio-disk0,\
cache=directsync,\
aio=native

    # Configure disk with VIRTIO drivers on it
    -drive file=/data/cd-roms/virtio-drivers-win_amd64.vfd,\
format=raw,\
if=none,\
id=drive-fdc0-0-0

    # Configure installation media disk
    -drive file=/data/os-images/windows10-x86_64.iso,\
format=raw,\
if=none,\
id=drive-ide0-0-0,\
readonly=on



########## GUEST DEVICE SETUP #######################################################################

     # Create PCI BLK device for the boot drive
     -device virtio-blk-pci,\
scsi=off,\
bus=pci.0,\
addr=0x5,\
drive=drive-virtio-disk0,\
id=virtio-disk0,\
bootindex=1

     -device ide-cd,\
bus=ide.0,\
unit=0,\
drive=drive-ide0-0-0,\
id=ide0-0-0

    -device rtl8139,\
netdev=hostnet0,\
id=net0,\
mac=52:54:00:06:8c:31,\
bus=pci.0,\
addr=0x3\

    -device isa-serial,\
chardev=charserial0,\
id=serial0

    -device usb-tablet,\
id=input0,\
bus=usb.0,\
port=1

    -device qxl-vga,\
id=video0,\
ram_size=67108864,\
vram_size=67108864,\
vram64_size_mb=0,\
vgamem_mb=16,\
max_outputs=1,\
bus=pci.0,\
addr=0x2

    -device virtio-balloon-pci,\
id=balloon0,\
bus=pci.0,\
addr=0x6

    ##### What does this do #####
    # TODO: ?
    -mon chardev=charmonitor,\
id=monitor,\
mode=control

    -chardev socket,\
id=charmonitor,\
path=/var/lib/libvirt/qemu/domain-1-windows/monitor.sock,\
server,\
nowait


    -chardev pty,\
id=charserial0

    -netdev tap,\
fd=21,\
id=hostnet0



########## DEFINE GLOBAL DRIVERS ####################################################################

    #### TODO: what are these?
    -global PIIX4_PM.disable_s4=1
    -global kvm-pit.lost_tick_policy=delay
    -global isa-fdc.driveA=drive-fdc0-0-0
    -global PIIX4_PM.disable_s3=1



########## MISC SETTINGS ############################################################################

     -nodefaults
     -msg timestamp=on
     ##### Do I need this? #####
     # TODO: ?
     -no-user-config
     ##### Freeze CPU at start up #####
     # TODO: why?
-S )


########## RUN COMMAND #############################################################################
 "${COMMAND[@]}"
####################################################################################################
