#!/bin/bash

COMMAND=(qemu-system-x86_64

    # comment here
    -enable-kvm


    -cpu host,\
kvm=off

    -m 2G

    -vga none

    -display none

    -smp 2,\
sockets=1,\
cores=2,\
threads=1

     -device vfio-pci,\
host=03:00.0,\
x-vga=on

     -device vfio-pci,\
host=4:00.0
)


"${COMMAND[@]}"
