#!/bin/bash

# Removes all temporary files created by emacs and vim. This can be potentially harmful if data
#   is unsaved. Use with caution

# TODO: implement a -r for recursive spotless

cd $PWD

if [ $# == 0 ]; then
   rm *~
else
    for var in "$@"
    do
	if [[ $var = */ ]]; then
	    rm $var*~
	else
	    rm $var/*~
	fi
   done
fi
