#!/bin/bash

# Creates a new qemu disk

QEMUIMG=qemu-img

#####################################################################################################
####################################### DISK IMAGE CREATION #########################################
#####################################################################################################
COMMAND=($QEMUIMG

    create

    # Set disk format to raw file for best performance
    -f raw

    # Specify options
    #-o 

    # Command input for the filename of the new disk
    $1

    # Command input for the size (in GB) of the new disk
    # Ex '20G'
    $2
)


########## RUN COMMAND #############################################################################
 "${COMMAND[@]}"
####################################################################################################

         
