#!/bin/bash

COMMAND=(qemu-system-x86_64

    -enable-kvm

    -m 1024

    -cpu host,\
kvm=off

    -uuid e1e39888-5f76-4ee0-860b-2503ac2adde0

    -smp 2,\
sockets=1,\
cores=2,\
threads=1

    -device vfio-pci,\
host=03:00.0,\
x-vga=on

    -device vfio-pci,\
host=04:00.0

    -vga none

    -display none
)


"${COMMAND[@]}"
