#!/bin/bash


mount -t proc /proc /mnt/vm-disk/proc
mount --rbind /sys /mnt/vm-disk/sys
mount --make-rslave /mnt/vm-disk/sys
mount --rbind /dev /mnt/vm-disk/dev
mount --make-rslave /mnt/vm-disk/dev

chroot /mnt/vm-disk/ /bin/bash
source /etc/profile
export PS1="(chroot) $PS1"
